apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-app
  namespace: codeargo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: codeargo
  source:
    path: base
    repoURL: https://github.com/andres-caylent/basic-app.git
    targetRevision: HEAD
    # helm:
    #   values: |
    #     image:
    #       tag: latest
    #     ingress:
    #       host: devopstoolkitseries.com
    #   version: v3
  destination:
    namespace: codeargo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

